
spring:
  profiles:
    active: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.108.142.167:3306/JJA1804?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: iot
    password: iot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
naming:
  implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  properties:
    hibernate.dialect: com.jane.utils.MySQL5DialectUTF8